### ISSUE TITLE
Add a "Start Game" button.

### ISSUE THREAD

**Issue by mariiaonokhina** [mariiaonokhina/snake-game-in-JS#1]

**Comment by ramumaha** [comment]
hey..
i am interested to work on this issue..Can you elaborate?
Thanks

**Comment by mariiaonokhina** [comment]
Sure. I was thinking of a screen with a "Start Game" button in the center that would appear right when the website loads. Clicking it will start the game. I would create a separate function that would change the canvas background color to whatever color you have in mind and make the button appear. Then, I would create an event listener that would trigger playGame() function when the button is clicked. Please, let me know if you need something. 😁
